//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto_Bilgisi
    {
        public string foto_Id { get; set; }
        public string foto { get; set; }
        public string foto_Urun_Id { get; set; }
    }
}
