//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Ticaret.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities4 : DbContext
    {
        public Entities4()
            : base("name=Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Favori_Bilgisi> Favori_Bilgisi { get; set; }
        public virtual DbSet<Kategori_Bilgisi> Kategori_Bilgisi { get; set; }
        public virtual DbSet<Marka_Bilgi> Marka_Bilgi { get; set; }
        public virtual DbSet<Sepet_Bilgisi> Sepet_Bilgisi { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urun_Bilgisi> Urun_Bilgisi { get; set; }
        public virtual DbSet<urun_Foto_Bilgisi> urun_Foto_Bilgisi { get; set; }
        public virtual DbSet<Uye_Bilgi> Uye_Bilgi { get; set; }
        public virtual DbSet<Satis_Bilgisi> Satis_Bilgisi { get; set; }
    }
}
