//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis_Bilgisi
    {
        public string satis_Id { get; set; }
        public string satis_Uye_Id { get; set; }
        public string satis_Urun_Id { get; set; }
        public int satis_Top_Fiyat { get; set; }
        public int satis_Urun_Fiyat { get; set; }
        public int satis_Urun_KDV { get; set; }
        public int satis_Urun_Kargo_Fiyat { get; set; }
    
        public virtual Urun_Bilgisi Urun_Bilgisi { get; set; }
        public virtual Uye_Bilgi Uye_Bilgi { get; set; }
    }
}
