//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet_Bilgisi
    {
        public string sepet_Id { get; set; }
        public string sepet_Uye_Id { get; set; }
        public string sepet_Urun_Id { get; set; }
        public int sepet_Urun_Fiyat { get; set; }
    
        public virtual Urun_Bilgisi Urun_Bilgisi { get; set; }
        public virtual Uye_Bilgi Uye_Bilgi { get; set; }
    }
}
