//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun_Bilgisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun_Bilgisi()
        {
            this.Favori_Bilgisi = new HashSet<Favori_Bilgisi>();
            this.Sepet_Bilgisi = new HashSet<Sepet_Bilgisi>();
            this.Satis_Bilgisi = new HashSet<Satis_Bilgisi>();
        }
    
        public string urun_Id { get; set; }
        public string urun_Marka_Id { get; set; }
        public string urun_Kategori_Id { get; set; }
        public string urun_Adi { get; set; }
        public int urun_Gelis_Fiyat { get; set; }
        public int urun_Satis_Fiyat { get; set; }
        public int urun_Stok { get; set; }
        public System.DateTime urun_Eklenme_Tarih { get; set; }
        public int urun_KDV { get; set; }
        public Nullable<int> urun_Satılan { get; set; }
        public string urun_Admin_Bilgi { get; set; }
        public string urun_Aciklama { get; set; }
        public string urun_Tanitim { get; set; }
        public string urun_Foto_Bilgisi { get; set; }
        public string urun_Foto1 { get; set; }
        public string urun_Foto_2 { get; set; }
        public string urun_foto_3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favori_Bilgisi> Favori_Bilgisi { get; set; }
        public virtual Kategori_Bilgisi Kategori_Bilgisi { get; set; }
        public virtual Marka_Bilgi Marka_Bilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet_Bilgisi> Sepet_Bilgisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis_Bilgisi> Satis_Bilgisi { get; set; }
        public virtual urun_Foto_Bilgisi urun_Foto_Bilgisi1 { get; set; }
        public virtual Uye_Bilgi Uye_Bilgi { get; set; }
    }
}
