//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Ticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye_Bilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uye_Bilgi()
        {
            this.Favori_Bilgisi = new HashSet<Favori_Bilgisi>();
            this.Sepet_Bilgisi = new HashSet<Sepet_Bilgisi>();
            this.Urun_Bilgisi = new HashSet<Urun_Bilgisi>();
            this.Satis_Bilgisi = new HashSet<Satis_Bilgisi>();
        }
    
        public string uye_Id { get; set; }
        public string uye_Ad_Soyad { get; set; }
        public string uye_E_Mail { get; set; }
        public string uye_Sifre { get; set; }
        public string uye_Adres_Bilgisi { get; set; }
        public Nullable<bool> uye_Admin_Bilgisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favori_Bilgisi> Favori_Bilgisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sepet_Bilgisi> Sepet_Bilgisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urun_Bilgisi> Urun_Bilgisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satis_Bilgisi> Satis_Bilgisi { get; set; }
    }
}
